apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  values:
    global:
      mtls:
        enabled: true
      
      controlPlaneSecurityEnabled: true

      #ingress:
      #  enabled: true
      #  annotations:
      #    "nginx.ingress.kubernetes.io/app-root": "/istio"
