version: 1

update_configs:
- package_manager: "terraform"
  directory: "/terraform/"
  update_schedule: "daily"

- package_manager: "github_actions"
  directory: "/"
  update_schedule: "daily"

- package_manager: "go:modules"
  directory: "/terraform/modules/scaleway/.kubernetes"
  update_schedule: "weekly"
  commit_message:
    prefix: "feat"
    include_scope: true
