helmRepos:
  nginxingress: https://kubernetes.github.io/ingress-nginx
  stable: https://kubernetes-charts.storage.googleapis.com
  loki: https://grafana.github.io/loki/charts
  netdata: https://netdata.github.io/helmchart
  k8sdashboard: https://kubernetes.github.io/dashboard

namespaces:
  monitoring:
  #kube-system

appsTemplates:
  default: &appTemplate
    test: true
    protected: false
    wait: true
    enabled: true

apps:
  dashboard:
    <<: *appTemplate
    namespace: monitoring
    chart: k8sdashboard/kubernetes-dashboard
    version: "~$K8SDASHBOARD_VERSION"
    valuesFile: dashboard.values.yaml

  logging:
    <<: *appTemplate
    namespace: monitoring
    chart: loki/loki-stack
    version: ~1.6
    valuesFile: logging.values.yaml

  netdata:
    <<: *appTemplate
    namespace: monitoring
    chart: netdata/netdata
    version: ~2.0.7
    valuesFile: netdata.values.yaml

  grafana:
    <<: *appTemplate
    namespace: monitoring
    chart: stable/grafana
    version: ~5.5
    valuesFile: grafana.values.yaml

  ingress:
    <<: *appTemplate
    namespace: kube-system
    chart: nginxingress/nginx-ingress
    version: ~ingress-nginx-2.11.3
    valuesFile: ingress.values.yaml
