name: Deploy
on:
  push:
    branches:
    - master

jobs:
  deploy:
    name: Terraform
    runs-on: ubuntu-latest
    steps:

    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment
      with:
        token: "${{ github.token }}"
        target-url: https://cluster.ironpeak.be/
        environment: production
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Checkout secrets
      uses: actions/checkout@v2
      with:
        repository: hazcod/infrastructure-state
        path: state/
        token: ${{ secrets.GITHUB_MERGE_TOKEN }}

    - name: Terraform - Init
      uses: hashicorp/terraform-github-actions@v0.7.1
      with:
        tf_actions_subcommand: "init"
        tf_actions_version: "latest"
        tf_actions_working_dir: terraform/

    - name: Terraform - Validate
      uses: hashicorp/terraform-github-actions@v0.7.1
      with:
        tf_actions_subcommand: "validate"
        tf_actions_version: "latest"
        tf_actions_working_dir: terraform/
  
    - name: Terraform - Plan
      uses: hashicorp/terraform-github-actions@v0.7.1
      with:
        tf_actions_subcommand: "plan"
        tf_actions_version: "latest"
        tf_actions_working_dir: terraform/
      env:
        TF_LOG: WARN
        TF_CLI_ARGS: "-state=state/terraform.tfstate"
        TF_ACTION_COMMENT: false
        TF_VAR_cloudflared_tunnel_token: ${{ secrets.TF_VAR_cloudflared_tunnel_token }}
        TF_VAR_cloudflare_email: ${{ secrets.TF_VAR_cloudflare_email }}
        TF_VAR_cloudflare_token: ${{ secrets.TF_VAR_cloudflare_token }}
        TF_VAR_github_org: ${{ secrets.TF_VAR_github_org }}
        TF_VAR_github_token: ${{ secrets.TF_VAR_github_token }}
        TF_VAR_scaleway_org: ${{ secrets. TF_VAR_scaleway_org }}
        TF_VAR_scaleway_accesstoken: ${{ secrets.TF_VAR_accesstoken }}
        TF_VAR_scaleway_secrettoken: ${{ secrets.TF_VAR_secrettoken }}
        TF_VAR_ssh_root_public_key: ${{ secrets.TF_VAR_ssh_root_public_key }}
        TF_VAR_ssh_root_private_key: ${{ secrets.TF_VAR_ssh_root_private_key }}
        TF_VAR_ssh_tech_public_key: ${{ secrets.TF_VAR_ssh_tech_public_key }}     

    - name: Terraform - Apply
      uses: hashicorp/terraform-github-actions@v0.7.1
      with:
        tf_actions_subcommand: "apply"
        tf_actions_version: "latest"
        tf_actions_working_dir: terraform/
      env:
        TF_LOG: WARN
        TF_ACTION_COMMENT: false
        TF_CLI_ARGS: "-state=state/terraform.tfstate"
        TF_VAR_cloudflared_tunnel_token: ${{ secrets.TF_VAR_cloudflared_tunnel_token }}
        TF_VAR_cloudflare_email: ${{ secrets.TF_VAR_cloudflare_email }}
        TF_VAR_cloudflare_token: ${{ secrets.TF_VAR_cloudflare_token }}
        TF_VAR_github_org: ${{ secrets.TF_VAR_github_org }}
        TF_VAR_github_token: ${{ secrets.TF_VAR_github_token }}
        TF_VAR_scaleway_org: ${{ secrets. TF_VAR_scaleway_org }}
        TF_VAR_scaleway_accesstoken: ${{ secrets.TF_VAR_accesstoken }}
        TF_VAR_scaleway_secrettoken: ${{ secrets.TF_VAR_secrettoken }}
        TF_VAR_ssh_root_public_key: ${{ secrets.TF_VAR_ssh_root_public_key }}
        TF_VAR_ssh_root_private_key: ${{ secrets.TF_VAR_ssh_root_private_key }}
        TF_VAR_ssh_tech_public_key: ${{ secrets.TF_VAR_ssh_tech_public_key }}     

    - uses: stefanzweifel/git-auto-commit-action@v2.5.0
      if: always()
      with:
        repository: state/
        commit_message: "feat(state): add new deployed state"
        branch: master
        file_pattern: terraform.tfstate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_MERGE_TOKEN }}
    
    - name: extract kubeconfig
      id: vars
      run: |
        echo ::set-output name=kubeconfig::$(cat terraform/kubeconfig | base64)
    
    - name: kubectl - kubernetes
      uses: steebchen/kubectl@1.0.1
      with:
        KUBE_CONFIG_DATA: ${{ vars.kubeconfig }}
        args: apply -f kubernetes/
      
    - name: Helmsman - apply
      uses: docker://praqma/helmsman:v3.1.0
      with:
        command: helmsman --apply -kubeconfig terraform/kubeconfig -f helm/helmfile.yaml'

    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment (success)
      if: success()
      with:
        token: "${{ github.token }}"
        target-url: https://cluster.ironpeak.be/
        environment: production
        state: "success"

    - uses: chrnorm/deployment-action@releases/v1
      name: Create GitHub deployment (failure)
      if: failure()
      with:
        token: "${{ github.token }}"
        target-url: https://cluster.ironpeak.be/
        environment: production
        state: "failure"
